name: nxtgm
channels:
  - conda-forge

dependencies:
  # Build tools
  - cmake
  - doctest 
  - cxx-compiler
  - boost-cpp
  - fmt
  - nlohmann_json
  - hihgs
  - xtensor
  # python-bindings
  - python
  - pybind11
  - xtensor-python
  - numpy