name: nxtgm
channels:
  - conda-forge

dependencies:
  # Build tools
  - cmake
  - doctest
  - cxx-compiler
  - boost-cpp
  - fmt
  - nlohmann_json
  - highs
  - xtensor
  - python
  - pybind11
  - xtensor-python
  - numpy
  - pytest
  - ninja
  - doxygen
  - sphinx
  - sphinx_rtd_theme
  - breathe
  - sphinx-sitemap
  - nodejs
