name: Build with conda
on:
    push:
    pull_request:

jobs:
  unix:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest

      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:


      - uses: actions/checkout@v3

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Install Conda environment from environment.yml
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'


      - name: Build docs
        shell: bash -l {0}
        run: |
          mkdir -p bld
          cd docs_doxygen
          npm install https://github.com/jothepro/doxygen-awesome-css#v2.2.1 --save-devs
          cd ../bld
          make docs

      - name: Build
        shell: bash -l {0}
        run: |
            cd bld
            cmake \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_TESTS=ON \
                -DBUILD_PYTHON=ON \
                -DBUILD_DOCS=ON \
            .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
            make -j ${{ steps.cpu-cores.outputs.count }}

      - name: Run C++ tets
        shell: bash -l {0}
        run: |
            cd bld
            ./tests/cpp_tests

      - name: Run Python tests
        shell: bash -l {0}
        run: |
            cd bld
            make python_tests

      - name: Build docs
        shell: bash -l {0}
        run: |
            cd docs_doxygen
            npm install https://github.com/jothepro/doxygen-awesome-css#v2.2.1 --save-dev
            cd ../bld
            make docs
