name: Build with conda
# on:
#   push:
#     branches:
#       - master
#   # For Pull-Requests, this runs the CI on merge commit
#   # of HEAD with the target branch instead on HEAD, allowing
#   # testing against potential new states which might have
#   # been introduced in the target branch last commits.
#   # See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
#  pull_request:

jobs:
  linux:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
        
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Install Conda environment from environment.yml
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'

      - name: Build 
        shell: bash -l {0}
        run: |
            mkdir bld
            cd bld
            cmake \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_TESTS=ON \
                -DBUILD_PYTHON=ON \
            .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
            make -j ${{ steps.cpu-cores.outputs.count }} 

      - name: Run C++ tets
        shell: bash -l {0}
        run: |
            cd bld
            ./tests/cpp_tests

      - name: Run Python tests
        shell: bash -l {0}
        run: |
            cd bld
            make python_tests


