name: Build with conda
on:
    push:
    pull_request:

jobs:
  linux:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest

      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:


      - uses: actions/checkout@v3

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Install Conda environment from environment.yml
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'

      - name: Build
        shell: bash -l {0}
        run: |
            mkdir bld
            cd bld
            cmake \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_TESTS=ON \
                -DBUILD_PYTHON=ON \
            .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
            make -j ${{ steps.cpu-cores.outputs.count }}

      - name: Run C++ tets
        shell: bash -l {0}
        run: |
            cd bld
            ./tests/cpp_tests

      - name: Run Python tests
        shell: bash -l {0}
        run: |
            cd bld
            make python_tests



  win:

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ windows-2019, windows-2022 ]

        steps:

            -   uses: actions/checkout@v2

            -   name: Install Conda environment from environment.yml
                uses: mamba-org/setup-micromamba@v1
                with:
                    environment-file: environment.yml
                    init-shell: >-
                        powershell
                    cache-environment: true
                    post-cleanup: 'all'


            -   name:  build
                shell: pwsh
                run: mkdir build
                    cmake .. ^
                    -G Ninja ^
                    -DCMAKE_BUILD_TYPE=Release ^
                    -DUILD_TESTS=ON ^
                    -DUILD_PYTHON=ON ^
                    -DDEPENDENCY_SEARCH_PREFIX="%CONDA_PREFIX%\Library" ^
                    -DCMAKE_PREFIX_PATH="%CONDA_PREFIX%\Library" ^
                    -DCMAKE_INSTALL_PREFIX="%CONDA_PREFIX%"

            -   name: run cpp tests
                shell: pwsh
                run: |
                    cd buil
                    ninja
                    .\tests\cpp_tests.exe

            -   name: "make python_tests"
                shell: pwsh
                run: |
                    cd build
                    ninja python_tests
